apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: hailtrace
data:
  KAFKA_BROKERS: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "storm-data-collector"
  KAFKA_TOPIC: "raw-weather-reports"
  REPORTS_BASE_URL: "http://mock-server:8080/"
  REPORT_TYPES: "torn,hail,wind"
  CRON_SCHEDULE: "0 0 * * *"
  LOG_LEVEL: "info"
