apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: hailtrace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: brendanvinson/storm-data-collector:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: collector-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
