apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: hailtrace
data:
  KAFKA_BROKERS: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "transformed-weather-data"
  KAFKA_GROUP_ID: "storm-data-api"
  PORT: "8080"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  SHUTDOWN_TIMEOUT: "10s"
  BATCH_SIZE: "50"
  BATCH_FLUSH_INTERVAL: "500ms"
