services:
  collector:
    build: !reset null
    image: brendanvinson/storm-data-collector:latest

  etl:
    build: !reset null
    image: brendanvinson/storm-data-etl:latest

  api:
    build: !reset null
    image: brendanvinson/storm-data-api:latest
