apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: brendanvinson/storm-data-collector
    newTag: latest
  - name: brendanvinson/storm-data-etl
    newTag: latest
  - name: brendanvinson/storm-data-api
    newTag: latest
