apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hailtrace

resources:
  # Postgres
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml

  # Mock Server
  - mock-server/deployment.yaml
  - mock-server/service.yaml

  # Collector
  - collector/configmap.yaml
  - collector/deployment.yaml
  - collector/service.yaml

  # ETL
  - etl/configmap.yaml
  - etl/deployment.yaml
  - etl/service.yaml

  # API
  - api/configmap.yaml
  - api/secret.yaml
  - api/deployment.yaml
  - api/service.yaml

  # Monitoring
  - monitoring/prometheus-config.yaml
  - monitoring/deployment.yaml
  - monitoring/service.yaml

  # Dashboard
  - dashboard/configmap.yaml
  - dashboard/deployment.yaml
  - dashboard/service.yaml

  # Kafka UI
  - kafka-ui/configmap.yaml
  - kafka-ui/deployment.yaml
  - kafka-ui/service.yaml
