apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: hailtrace
data:
  KAFKA_CLUSTERS_0_NAME: "storm-kafka"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
